language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest 'MasterMoviesMPP Node.py ingest'
  - pytest 'MasterMoviesMPP Node.py transode'
  - pytest 'MasterMoviesMPP Node.py export'
