language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE MasterMoviesMPP;'
  - mysql -e MasterMvoiesMPP < MasterMoviesMPP.sql
script:
  - python 'MasterMoviesMPP Node.py' ingest
  - python 'MasterMoviesMPP Node.py' transcode
  - python 'MasterMoviesMPP Node.py' export
