language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_install:
  - sudo mysql -u root "CREATE DATABASE MasterMoviesMPP;"
  - sudo mysql -u root "USE MasterMoviesMPP;" < MasterMoviesMPP.sql
script:
  - python 'MasterMoviesMPP Node.py' ingest
  - python 'MasterMoviesMPP Node.py' transcode
  - python 'MasterMoviesMPP Node.py' export
