language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_install:
  - sudo mysql -e "CREATE DATABASE MasterMoviesMPP;"
  - sudo mysql -e MasterMoviesMPP < file.sql
script:
  - pytest 'MasterMoviesMPP Node.py' ingest
  - pytest 'MasterMoviesMPP Node.py' transode
  - pytest 'MasterMoviesMPP Node.py' export
