language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE MasterMoviesMPP;'
  - sudo mysql MasterMoviesMPP < MasterMoviesMPP.sql
  - echo "SHOW DATABASES;" | mysql
  - sudo mkdir work work/source work/ingest work/transcode work/export work/media
script:
  - python 'MasterMoviesMPP Node.py' ingest --build
  - python 'MasterMoviesMPP Node.py' transcode --build
  - python 'MasterMoviesMPP Node.py' export --build
